### ISSUE TITLE
i got Error .

### ISSUE THREAD

**Issue by Mehran** [riptidewave93/DO-AutoVPN#8]
```
Deploy Error: Size 
Traceback (most recent call last):
  File "deploy.py", line 102, in <module>
    droplet.create()
  File "/usr/local/lib/python3.6/dist-packages/digitalocean/Droplet.py", line 564, in create
    data = self.get_data("droplets/", type=POST, params=data)
  File "/usr/local/lib/python3.6/dist-packages/digitalocean/Droplet.py", line 162, in get_data
    data = super(Droplet, self).get_data(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/digitalocean/baseapi.py", line 196, in get_data
    raise DataReadError(msg)
digitalocean.DataReadError: Size 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deploy.py", line 105, in <module>
    droplet.destroy()
  File "/usr/local/lib/python3.6/dist-packages/digitalocean/Droplet.py", line 415, in destroy
    return self.get_data("droplets/%s" % self.id, type=DELETE)
  File "/usr/local/lib/python3.6/dist-packages/digitalocean/Droplet.py", line 162, in get_data
    data = super(Droplet, self).get_data(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/digitalocean/baseapi.py", line 185, in get_data
    raise NotFoundError()
digitalocean.NotFoundError
```

**Comment by riptidewave93** [comment]
This is a sign either you had issues connecting to DigitalOcean, or you may have used an invalid API token.
